In [334]:
## Dataset: https://github.com/krishnaik06/5-Days-Live-EDA-and-Feature-Engineering/tree/main/Flight%20Prediction

In [335]:
# importing the basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [336]:
train_df=pd.read_excel("C:/My laptop files/projects/EDA/data/Flight Prediction/Data_Train.xlsx")

In [337]:
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [338]:
train_df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [339]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [340]:
test_df=pd.read_excel("C:/My laptop files/projects/EDA/data/Flight Prediction/Test_set.xlsx")
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [341]:
final_df=pd.concat([train_df, test_df], ignore_index=True)

In [342]:
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [343]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [344]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.1+ MB

## feature engineering

In [345]:
final_df["Date_of_Journey"].str.split('/').str[0]

0        24
1         1
2         9
3        12
4        01
         ..
13349     6
13350    27
13351     6
13352     6
13353    15
Name: Date_of_Journey, Length: 13354, dtype: object

In [346]:
final_df["Date"]=final_df["Date_of_Journey"].str.split('/').str[0]
final_df["Month"]=final_df["Date_of_Journey"].str.split('/').str[1]
final_df["Year"]=final_df["Date_of_Journey"].str.split('/').str[2]

In [347]:
final_df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019

In [348]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

In [349]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int32
 12  Month            13354 non-null  int32
 13  Year             13354 non-null  int32
dtypes: float64(1), int32(3), object(10)
memory usage: 1.3+ MB

In [350]:
## For the specific column
final_df["Date"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 13354 entries, 0 to 13353
Series name: Date
Non-Null Count  Dtype
--------------  -----
13354 non-null  int32
dtypes: int32(1)
memory usage: 52.3 KB

In [351]:
final_df.drop("Date_of_Journey",axis=1,inplace=True)

In [352]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019

In [353]:
final_df["Arrival_Time"]=final_df["Arrival_Time"].apply(lambda x : x.split(' ')[0])

In [354]:
final_df["Arrival_Time"]

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
13349    20:25
13350    16:55
13351    04:25
13352    19:15
13353    19:15
Name: Arrival_Time, Length: 13354, dtype: object

In [355]:
final_df["Arrival_hour"]=final_df["Arrival_Time"].str.split(':').str[0]
final_df["Arrival_min"]=final_df["Arrival_Time"].str.split(':').str[1]

In [356]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10

In [357]:
final_df["Arrival_hour"]=final_df["Arrival_hour"].astype(int)
final_df["Arrival_min"]=final_df["Arrival_min"].astype(int)

In [358]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int32
 11  Month            13354 non-null  int32
 12  Year             13354 non-null  int32
 13  Arrival_hour     13354 non-null  int32
 14  Arrival_min      13354 non-null  int32
dtypes: float64(1), int32(5), object(9)
memory usage: 1.3+ MB

In [359]:
final_df.drop("Arrival_Time",axis=1,inplace=True)

In [360]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10

In [361]:
final_df["Dep_Time"]=final_df["Dep_Time"].apply(lambda x : x.split(' ')[0])

In [362]:
final_df["Dep_hour"]=final_df["Dep_Time"].str.split(':').str[0]
final_df["Dep_min"]=final_df["Dep_Time"].str.split(':').str[1]

In [363]:
final_df["Dep_hour"]=final_df["Dep_hour"].astype(int)
final_df["Dep_min"]=final_df["Dep_min"].astype(int)

In [364]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20

In [365]:
final_df.drop("Dep_Time",axis=1,inplace=True)

In [366]:
final_df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50

In [367]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int32
 9   Month            13354 non-null  int32
 10  Year             13354 non-null  int32
 11  Arrival_hour     13354 non-null  int32
 12  Arrival_min      13354 non-null  int32
 13  Dep_hour         13354 non-null  int32
 14  Dep_min          13354 non-null  int32
dtypes: float64(1), int32(7), object(7)
memory usage: 1.2+ MB

In [368]:
final_df["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [369]:
final_df["Total_Stops"]=final_df["Total_Stops"].map({"non-stop":0,
                                                    "1 stop":1,
                                                   "2 stops":2,
                                                   "3 stops":3,
                                                   "nan":1,
                                                   "4 stops":4})

In [370]:
final_df["Total_Stops"].fillna(1, inplace=True)
final_df["Total_Stops"] = final_df["Total_Stops"].astype(int)

In [371]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13354 non-null  int32
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int32
 9   Month            13354 non-null  int32
 10  Year             13354 non-null  int32
 11  Arrival_hour     13354 non-null  int32
 12  Arrival_min      13354 non-null  int32
 13  Dep_hour         13354 non-null  int32
 14  Dep_min          13354 non-null  int32
dtypes: float64(1), int32(8), object(6)
memory usage: 1.1+ MB

In [372]:
final_df.drop("Route",axis=1,inplace=True)

In [373]:
final_df["Additional_Info"].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [374]:
# extract hours
final_df["duration_hour"] = final_df["Duration"].str.extract('(\d+)h')

# extract minutes
final_df["duration_min"] = final_df["Duration"].str.extract('(\d+)m')

# fill missing values
final_df["duration_hour"] = final_df["duration_hour"].fillna(0).astype(int)
final_df["duration_min"] = final_df["duration_min"].fillna(0).astype(int)

# total minutes
final_df["duration_total_min"] = final_df["duration_hour"] * 60 + final_df["duration_min"]

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
C:\Users\santo\AppData\Local\Temp\ipykernel_20760\2122315128.py:2: SyntaxWarning: invalid escape sequence '\d'
  final_df["duration_hour"] = final_df["Duration"].str.extract('(\d+)h')
C:\Users\santo\AppData\Local\Temp\ipykernel_20760\2122315128.py:5: SyntaxWarning: invalid escape sequence '\d'
  final_df["duration_min"] = final_df["Duration"].str.extract('(\d+)m')

In [375]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min,duration_total_min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50,7,25,445
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882.0,9,6,2019,4,25,9,25,19,0,1140
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218.0,12,5,2019,23,30,18,5,5,25,325
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302.0,1,3,2019,21,35,16,50,4,45,285

In [376]:
final_df.drop("Duration" , axis=1 , inplace=True)

In [377]:
final_df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min,duration_total_min
0,IndiGo,Banglore,New Delhi,0,No info,3897.0,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,2,No info,7662.0,1,5,2019,13,15,5,50,7,25,445

In [378]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Airline             13354 non-null  object
 1   Source              13354 non-null  object
 2   Destination         13354 non-null  object
 3   Total_Stops         13354 non-null  int32
 4   Additional_Info     13354 non-null  object
 5   Price               10683 non-null  float64
 6   Date                13354 non-null  int32
 7   Month               13354 non-null  int32
 8   Year                13354 non-null  int32
 9   Arrival_hour        13354 non-null  int32
 10  Arrival_min         13354 non-null  int32
 11  Dep_hour            13354 non-null  int32
 12  Dep_min             13354 non-null  int32
 13  duration_hour       13354 non-null  int32
 14  duration_min        13354 non-null  int32
 15  duration_total_min  13354 non-null  int32
dtypes: float64(1), int32(11), object(4)
memory usage: 1.1+ MB

In [379]:
final_df["Airline"].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [380]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

In [381]:
final_df["Airline"]=labelencoder.fit_transform(final_df["Airline"])
final_df["Source"]=labelencoder.fit_transform(final_df["Source"])
final_df["Destination"]=labelencoder.fit_transform(final_df["Destination"])
final_df["Additional_Info"]=labelencoder.fit_transform(final_df["Additional_Info"])

In [382]:
final_df.shape

(13354, 16)

In [383]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min,duration_total_min
0,3,0,5,0,8,3897.0,24,3,2019,1,10,22,20,2,50,170
1,1,3,0,2,8,7662.0,1,5,2019,13,15,5,50,7,25,445
2,4,2,1,2,8,13882.0,9,6,2019,4,25,9,25,19,0,1140
3,3,3,0,1,8,6218.0,12,5,2019,23,30,18,5,5,25,325
4,3,0,5,1,8,13302.0,1,3,2019,21,35,16,50,4,45,285

In [384]:
pd.get_dummies(final_df,columns=['Airline','Source','Destination','Additional_Info'],drop_first=True)

,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,0,3897.0,24,3,2019,1,10,22,20,2,...,True,False,False,False,False,False,False,False,True,False
1,2,7662.0,1,5,2019,13,15,5,50,7,...,False,False,False,False,False,False,False,False,True,False
2,2,13882.0,9,6,2019,4,25,9,25,19,...,False,False,False,False,False,False,False,False,True,False
3,1,6218.0,12,5,2019,23,30,18,5,5,...,False,False,False,False,False,False,False,False,True,False
4,1,13302.0,1,3,2019,21,35,16,50,4,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,1,NaN,6,6,2019,20,25,20,30,23,...,False,False,False,False,False,False,False,False,True,False
13350,0,NaN,27,3,2019,16,55,14,20,2,...,False,False,False,False,False,False,False,False,True,False
13351,1,NaN,6,3,2019,4,25,21,50,6,...,False,False,False,False,False,False,False,False,True,False
13352,1,NaN,6,3,2019,19,15,4,0,15,...,False,False,False,False,False,False,False,False,True,False
13353,1,NaN,15,6,2019,19,15,4,55,14,...,False,False,False,False,False,False,False,False,True,False

In [385]:
final_df.shape

(13354, 16)